name: Build ROM
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpng-dev libelf-dev zlib1g-dev binutils-arm-none-eabi dos2unix

      - name: Install agbcc
        run: |
          git clone https://github.com/pret/agbcc
          cd agbcc
          ./build.sh
          ./install.sh ../
          cd ..

      - name: Fix all line endings
        run: find . -type f -name "*" -print0 | xargs -0 dos2unix

      - name: Build ROM
        run: |
          make clean
          make -j$(nproc) WERROR=0 WARNINGS=0

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: pokedust-rom
          path: "*.gba"
